version: '2'
services:
  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: letsencryptcert
      port_rules:
      - hostname: drone.hutter.cloud
        path: ''
        priority: 1
        protocol: https
        service: drone-server
        source_port: 8000
        target_port: 8000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  drone-server:
    scale: 1
    start_on_create: true
  drone-agent:
    start_on_create: true
