version: '2'
services:
  proxy:
    image: rancher/lb-service-haproxy:latest
    ports:
    - 8443:8443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      cloud.hutter.autofw.ip.firewall.dstnat: protocol=tcp,dstport=8443,ininterface=sfp1
      cloud.hutter.autofw.ip.dns.static.comment: reverse proxy services
      cloud.hutter.autofw.enable: 'true'
      cloud.hutter.autofw.ip.dns.static: name=calibre.hutter.cloud:name=usenet.hutter.cloud:name=status.hutter.cloud:name=scm.hutter.cloud:name=pizza-api.hutter.cloud:name=pizza-media.hutter.cloud
      io.rancher.container.create_agent: 'true'
  reverse-nginx:
    image: sebastianhutter/nginx:latest
    environment:
      CONFIG_URL: http://nas.barfoot.local/dnas/docker/nginx.conf
      INDEX_URL: http://nas.barfoot.local/dnas/docker/index.html
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      cloud.hutter.watcher.ip.enable: true
      cloud.hutter.watcher.ip.reboot: status-statuspage-1
