version: '2'
services:
  proxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        timeout server 1800s
        timeout client 1800s
      default_cert: letsencryptcert
      port_rules:
      - hostname: usenet.hutter.cloud
        path: ''
        priority: 1
        protocol: https
        service: reverse-nginx
        source_port: 8443
        target_port: 80
      - hostname: barfoot.duckdns.org
        priority: 2
        protocol: https
        service: reverse-nginx
        source_port: 8443
        target_port: 80
      - hostname: calibre.hutter.cloud
        path: ''
        priority: 3
        protocol: https
        service: reverse-nginx
        source_port: 8443
        target_port: 80
      - hostname: status.hutter.cloud
        path: ''
        priority: 3
        protocol: https
        service: status/statuspage
        source_port: 8443
        target_port: 8080
      - hostname: scm.hutter.cloud
        path: ''
        priority: 3
        protocol: https
        service: scm-webdav/nginx
        source_port: 8443
        target_port: 80
      - hostname: pizza-media.hutter.cloud
        path: ''
        priority: 3
        protocol: https
        service: ffhs-pizza/pizza-media
        source_port: 8443
        target_port: 80
      - hostname: pizza-api.hutter.cloud
        path: ''
        priority: 3
        protocol: https
        service: ffhs-pizza/pizza-api
        source_port: 8443
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  reverse-nginx:
    scale: 1
    start_on_create: true
