version: '2'
services:
  tikautofw:
    image: sebastianhutter/tikautofw:aafa3670
    environment:
      AUTOFW_SCHEDULE:
      AUTOFW_LOGLEVEL:
      AUTOFW_VAULT_SERVER:
      AUTOFW_VAULT_ROLE_ID:
      AUTOFW_MIKROTIK_ADDRESS:
      AUTOFW_RANCHER_API_URL:
      AUTOFW_VAULT_SECRET_ID:
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '5'
    labels:
      io.rancher.container.pull_image: always
