version: '2'
volumes:
  letsencrypt-certificates-vault:
    driver: nfs
    driver_opts:
      share: nas.barfoot.local:/volume1/docker/letsencrypt-certificates-vault
  letsencrypt-certificates-openvpn:
    driver: nfs
    driver_opts:
      share: nas.barfoot.local:/volume1/docker/letsencrypt-certificates-openvpn
  letsencrypt-certificates:
    driver: nfs
    driver_opts:
      share: nas.barfoot.local:/volume1/docker/letsencrypt-certificates
  letsencrypt-certificates-external:
    driver: nfs
    driver_opts:
      share: nas.barfoot.local:/volume1/docker/letsencrypt-certificates-external
  letsencrypt-certificates-nas:
    driver: nfs
    driver_opts:
      share: nas.barfoot.local:/volume1/docker/letsencrypt-certificates-nas
services:
  letsencrypt-openvpn:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      CERT_NAME: letsencryptcert-openvpn
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: openvpn.hutter.cloud
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: mail@sebastian-hutter.ch
      EULA: 'Yes'
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
    volumes:
    - letsencrypt-certificates-openvpn:/etc/letsencrypt/production/certs
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  letsencrypt-vault:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      CERT_NAME: letsencryptcert-vault
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: vault.hutter.cloud
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: mail@sebastian-hutter.ch
      EULA: 'Yes'
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
    volumes:
    - letsencrypt-certificates-vault:/etc/letsencrypt/production/certs
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      CERT_NAME: letsencryptcert
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: usenet.hutter.cloud,ci.hutter.cloud,calibre.hutter.cloud,status.hutter.cloud,password.hutter.cloud,scm.hutter.cloud,drone.hutter.cloud,pizza-api.hutter.cloud,pizza-media.hutter.cloud
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: mail@sebastian-hutter.ch
      EULA: 'Yes'
      GANDI_API_KEY: ''
      OVH_APPLICATION_KEY: ''
      OVH_APPLICATION_SECRET: ''
      OVH_CONSUMER_KEY: ''
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
      VULTR_API_KEY: ''
    volumes:
    - letsencrypt-certificates:/etc/letsencrypt/production/certs
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  letsencrypt-external:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      CERT_NAME: letsencryptcert-external
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: rancher.hutter.cloud
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: mail@sebastian-hutter.ch
      EULA: 'Yes'
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
    volumes:
    - letsencrypt-certificates-external:/etc/letsencrypt/production/certs
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
  letsencrypt-nas:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      CERT_NAME: letsencryptcert-nas
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: nas.hutter.cloud
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: mail@sebastian-hutter.ch
      EULA: 'Yes'
      PROVIDER: Route53
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
    volumes:
    - letsencrypt-certificates-external:/etc/letsencrypt/production/certs
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
