version: '2'
volumes:
  openvpn-openvpnas-etc:
    driver: nfs
    driver_opts:
      share: nas.barfoot.local:/volume1/docker/openvpn-openvpnas-etc
services:
  openvpnas:
    cap_add:
    - NET_ADMIN
    - NET_RAW
    image: sebastianhutter/openvpnas:latest
    environment:
      OPENVPN_PASSWORD:
    devices:
    - /dev/net/tun:/dev/net/tun:rwm
    stdin_open: true
    network_mode: host
    volumes:
    - openvpn-openvpnas-etc:/usr/local/openvpn_as/etc
    tty: true
    ports:
    - 1194:1194/tcp
    - 443:443/tcp
    - 943:943/tcp
    - 1194:1194/udp
    labels:
      cloud.hutter.autofw.ip.dns.static.comment: openvpn service
      cloud.hutter.autofw.ip.firewall.dstnat: protocol=tcp,dstport=443,ininterface=sfp1:protocol=udp,dstport=1194,ininterface=sfp1
      cloud.hutter.autofw.enable: 'true'
      cloud.hutter.autofw.ip.dns.static: name=openvpn.hutter.cloud
      cloud.hutter.autofw.ip.firewall.dstnat.comment: openvpn services tcp943-admin tcp944-client tcp443-vpn udp1194-vpn
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: last-gen=true
      cloud.hutter.watcher.ip.enable: true
      cloud.hutter.watcher.ip.reboot: status-statuspage-1
